### ISSUE TITLE
Ruby 4.0 compatibility: 'error_handler' should be declared with 'noreturn'

### ISSUE THREAD

**Issue by kfa-wtag** [rgeo/rgeo#391]
While attempting to use rgeo with Ruby 4.0.0, the native extension fails to compile due to usage of Ruby C API internals that are no longer available.

Specifically, Ruby 4.0 removes `typed_flag` from `struct RTypedData`, which causes compilation errors in `ext/geos_c_impl`.

A related fix was introduced in commit 9297158, which addresses some Ruby C API warnings (for example, around function attributes such as `noreturn`). However, the released gem (rgeo 3.0.1) is still not fully compatible with Ruby 4.0, and the build currently fails.

As a result, rgeo cannot be installed on Ruby 4.0.0, which also blocks dependent gems such as `activerecord-postgis-adapter`.

It would be greatly appreciated if Ruby 4.0 compatibility could be completed and released.

**Error output**

> globals.c:61:1: warning: function 'error_handler' could be declared with attribute 'noreturn' [-Wmissing-noreturn]
>    61 | {
>       | ^
> factory.c:558:7: error: no member named 'typed_flag' in 'struct RTypedData'
>   558 |   if (RGEO_FACTORY_TYPEDDATA_P(orig)) {
>       |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ./factory.h:103:4: note: expanded from macro 'RGEO_FACTORY_TYPEDDATA_P'
>   103 |   (_RGEO_TYPEDDATA_P(object, &rgeo_factory_type))
>       |    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ./factory.h:108:50: note: expanded from macro '_RGEO_TYPEDDATA_P'
>   108 |   (TYPE(object) == T_DATA && RTYPEDDATA(object)->typed_flag == 1 &&            \
>       |                              ~~~~~~~~~~~~~~~~~~  ^
> factory.c:558:7: warning: comparison between pointer and integer ('VALUE' (aka 'unsigned long') and 'const rb_data_type_t *' (aka 'const struct rb_data_type_struct *')) [-Wpointer-integer-compare]
>   558 |   if (RGEO_FACTORY_TYPEDDATA_P(orig)) {
>       |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ./factory.h:103:4: note: expanded from macro 'RGEO_FACTORY_TYPEDDATA_P'
>   103 |   (_RGEO_TYPEDDATA_P(object, &rgeo_factory_type))
>       |    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ./factory.h:109:29: note: expanded from macro '_RGEO_TYPEDDATA_P'
>   109 |    RTYPEDDATA(object)->type == data_type)
>       |    ~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~
> factory.c:829:22: error: no member named 'typed_flag' in 'struct RTypedData'
>   829 |   if (NIL_P(type) && RGEO_GEOMETRY_TYPEDDATA_P(obj) &&
>       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ./factory.h:105:4: note: expanded from macro 'RGEO_GEOMETRY_TYPEDDATA_P'
>   105 |   (_RGEO_TYPEDDATA_P(object, &rgeo_geometry_type))
>       |    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ./factory.h:108:50: note: expanded from macro '_RGEO_TYPEDDATA_P'
>   108 |   (TYPE(object) == T_DATA && RTYPEDDATA(object)->typed_flag == 1 &&            \
>       |                              ~~~~~~~~~~~~~~~~~~  ^
> factory.c:829:22: warning: comparison between pointer and integer ('VALUE' (aka 'unsigned long') and 'const rb_data_type_t *' (aka 'const struct rb_data_type_struct *')) [-Wpointer-integer-compare]
>   829 |   if (NIL_P(type) && RGEO_GEOMETRY_TYPEDDATA_P(obj) &&
>       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ./factory.h:105:4: note: expanded from macro 'RGEO_GEOMETRY_TYPEDDATA_P'
>   105 |   (_RGEO_TYPEDDATA_P(object, &rgeo_geometry_type))
>       |    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ./factory.h:109:29: note: expanded from macro '_RGEO_TYPEDDATA_P'
>   109 |    RTYPEDDATA(object)->type == data_type)
>       |    ~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~
> factory.c:931:10: error: no member named 'typed_flag' in 'struct RTypedData'
>   931 |   return RGEO_GEOMETRY_TYPEDDATA_P(obj) ? 1 : 0;
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ./factory.h:105:4: note: expanded from macro 'RGEO_GEOMETRY_TYPEDDATA_P'
>   105 |   (_RGEO_TYPEDDATA_P(object, &rgeo_geometry_type))
>       |    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ./factory.h:108:50: note: expanded from macro '_RGEO_TYPEDDATA_P'
>   108 |   (TYPE(object) == T_DATA && RTYPEDDATA(object)->typed_flag == 1 &&            \
>       |                              ~~~~~~~~~~~~~~~~~~  ^
> factory.c:931:10: warning: comparison between pointer and integer ('VALUE' (aka 'unsigned long') and 'const rb_data_type_t *' (aka 'const struct rb_data_type_struct *')) [-Wpointer-integer-compare]
>   931 |   return RGEO_GEOMETRY_TYPEDDATA_P(obj) ? 1 : 0;
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ./factory.h:105:4: note: expanded from macro 'RGEO_GEOMETRY_TYPEDDATA_P'
>   105 |   (_RGEO_TYPEDDATA_P(object, &rgeo_geometry_type))
>       |    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ./factory.h:109:29: note: expanded from macro '_RGEO_TYPEDDATA_P'
>   109 |    RTYPEDDATA(object)->type == data_type)
>       |    ~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~
> factory.c:945:10: error: no member named 'typed_flag' in 'struct RTypedData'
>   945 |   return RGEO_GEOMETRY_TYPEDDATA_P(obj)
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ./factory.h:105:4: note: expanded from macro 'RGEO_GEOMETRY_TYPEDDATA_P'
>   105 |   (_RGEO_TYPEDDATA_P(object, &rgeo_geometry_type))
>       |    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ./factory.h:108:50: note: expanded from macro '_RGEO_TYPEDDATA_P'
>   108 |   (TYPE(object) == T_DATA && RTYPEDDATA(object)->typed_flag == 1 &&            \
>       |                              ~~~~~~~~~~~~~~~~~~  ^
> factory.c:945:10: warning: comparison between pointer and integer ('VALUE' (aka 'unsigned long') and 'const rb_data_type_t *' (aka 'const struct rb_data_type_struct *')) [-Wpointer-integer-compare]
>   945 |   return RGEO_GEOMETRY_TYPEDDATA_P(obj)
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ./factory.h:105:4: note: expanded from macro 'RGEO_GEOMETRY_TYPEDDATA_P'
>   105 |   (_RGEO_TYPEDDATA_P(object, &rgeo_geometry_type))
>       |    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ./factory.h:109:29: note: expanded from macro '_RGEO_TYPEDDATA_P'
>   109 |    RTYPEDDATA(object)->type == data_type)
>       |    ~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~
> 4 warnings and 4 errors generated.
> make: *** [factory.o] Error 1
> make: *** Waiting for unfinished jobs....
> 1 warning generated.
> 
> make failed, exit code 2

**Environment**

Ruby: 4.0.0 (built from ruby/ruby master)

rgeo: 3.0.1

activerecord-postgis-adapter: 11.1.1

rgeo-activerecord: 8.1.0

OS: macOS (Apple Silicon)

Ruby installed via: rbenv

**Comment by kfa-wtag** [comment]
> You are basically asking for a new release including the fix, right? Or did I miss something else ?

@BuonOmo Yes, exactly — the request is for a new release that includes the existing fixes and ensures full compatibility with Ruby 4.0

**Comment by BuonOmo** [comment]
The new version 3.1.0 is published, and working on RGeo's CI

**Comment by kfa-wtag** [comment]
@BuonOmo Thank you for the support. The issue has been resolved and `Ruby 4.0` is up and running with `rgeo 3.1.0`
