### ISSUE TITLE
Rails 5 Support

### ISSUE THREAD

**Issue by pitamonster** [rgeo/rgeo#137]
I'm not sure this is directly a Rails 5 issue, but I am getting the following error. Note how after I assign 'location_point' to 'site', the 'site' object no longer supports #inspect. Also trying to access site.location_point gives the error. I'd appreciate any help in troubleshooting in case this doesn't look like a Rails 5 support problem. But everything was working in Rails 4.2 which is what raises the suspicion...Actually after going through and looking, it seems like the adapter maybe is wrongly passing the RGeo object into the wktparser and that is what is causing the parse error. But I'm not sure if that is the root of the problem. Thanks in advance.

> 2.3.0 :008 > site
>  => Site id: nil, user_id: nil, utility_name: "Con Ed", utility_rate: nil, annual_kwh_usage: nil, created_at: nil, updated_at: nil, location_point: nil
> 2.3.0 :009 > site.location_point = params["location_point"]
>  => RGeo::Geos::CAPIPointImpl:0x22a24a0 "POINT (-73.96260784645612 40.67387551422036)" 
> 2.3.0 :010 > site
> (Object doesn't support #inspect)
>  =>  
> 2.3.0 :011 > site.location_point
> NoMethodError: undefined method `[]' for #<RGeo::Geos::CAPIPointImpl:0x00000004544940>
>         from /usr/local/rvm/gems/ruby-2.3.0/gems/rgeo-0.5.2/lib/rgeo/wkrep/wkb_parser.rb:106:in`parse'
>         from /usr/local/rvm/gems/ruby-2.3.0/bundler/gems/activerecord-postgis-adapter-f6cdd732e621/lib/active_record/connection_adapters/postgis/oid/spatial.rb:91:in `cast_value'
>         from /usr/local/rvm/gems/ruby-2.3.0/gems/activemodel-5.0.0.beta1/lib/active_model/type/value.rb:36:in`cast'
>         from /usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0.beta1/lib/active_record/attribute.rb:150:in `type_cast'
>         from /usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0.beta1/lib/active_record/attribute.rb:38:in`value'
>         from /usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0.beta1/lib/active_record/attribute_set.rb:42:in `fetch_value'
>         from /usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0.beta1/lib/active_record/attribute_methods/read.rb:78:in`_read_attribute'
>         from /usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0.beta1/lib/active_record/attribute_methods/read.rb:48:in `__temp__c6f636164796f6e6f507f696e647'
>         from (irb):11

**Comment by vladson** [comment]
@pitamonster I've encountered the same issue right now. I'll try coping with it. Did you succeed?

**Comment by pitamonster** [comment]
@vladson I did not succeed. I ended up just going back to Rails 4.2 for my current project after running into this issue--since I was running into Rails 5 support problems in other gems too--both related (activerecord-postgis-adapter which this issue may have something to do with) and unrelated.

**Comment by teeparham** [comment]
This gem is independent of active record. Try the release versions of the active record adapter gems for Rails 5 support. There's a Rails 5-compatible release of `activerecord-postgis-adapter` now.

https://github.com/rgeo/activerecord-postgis-adapter
